#!/bin/sh
# 
# ------------->>WARNING!!!!:<<---------------
# The following is a poorly written script to aid me in making trivial commits  
# to my local repo. It does this by adding all changes & commiting with
# user inputted message.
# ----->>NOT MEANT FOR EXTERNAL USE!!<<-------
#
# Usage:
# ac "COMMIT_MESSAGE"
#

PROJECT_ROOT_DIR=/home/fm/dev/web/overload

cd $PROJECT_ROOT_DIR || exit
git add .
git commit -m "$1"

exit 0